### ISSUE TITLE
Are contributions still welcome?

### ISSUE THREAD

**Issue by Tomcat-42** [Devolutions/conan-rs#16]
First, great library!!!

What is the state of this project? It is still maintaned?

Cheers :partying_face: , Pablo.

**Comment by awakecoding** [comment]
I have to admit we haven't giving it much love recently and that I somehow missed a few open pull requests, but let me get that fixed. The project has pretty much been doing what we need it to for a while, so we mostly see incremental improvements being contributed as people use it in different ways

**Comment by ravenexp** [comment]
> The project has pretty much been doing what we need it to for a while, so we mostly see incremental improvements being contributed as people use it in different ways

BTW, I was working on Conan 2.0 support for `conan-rs` in the meantime, but as my smaller PRs took so long to review I basically decided to start from scratch and this is the result: <https://github.com/ravenexp/conan2-rs>. It is not a fork of `conan-rs`, but rather an independent implementation.

This is not an advertisement, `conan-rs` served me well for years, but then I had a hard requirement to switch to Conan 2.0 in a short time frame. I hope that my work will be useful for someone.

**Comment by Tomcat-42** [comment]
> The project has pretty much been doing what we need it to for a while, so we mostly see incremental improvements being contributed as people use it in different ways

Sure, it's already a great lib @awakecoding , thanks!!! In my use case I would need conan to build a cpp legacy project, so then after I could use the generated libs in my Rust code. Do you think this feature is in the scope of conan-rs?

**Comment by Tomcat-42** [comment]
> This is not an advertisement, `conan-rs` served me well for years, but then I had a hard requirement to switch to Conan 2.0 in a short time frame. I hope that my work will be useful for someone.

I liked the API of [conan2-rs](https://github.com/ravenexp/conan2-rs). It almost made me switch the old cpp project that I'm working to conan2 prior to it's Rust integration.

**Comment by awakecoding** [comment]
@Tomcat-42 let me know what you need to revive this project, and make a new release published in crates.io (it's been a while). Are there other improvements you'd need to submit from conan2-rs?

**Comment by Tomcat-42** [comment]
I think the main improvement will be the ability to run builds from conan. 

I'm biased because that's exacly my use case, but a lot of people use conan like this:

```bash
conan install . <ARGS> && conan build .
```

So IMO this will be of good use for the general user base.
