### ISSUE TITLE
BuildDependency with multiple include directories doesn't allow for full usage.

### ISSUE THREAD

**Issue by raspofabs** [Devolutions/conan-rs#8]
https://github.com/Devolutions/conan-rs/blob/65a4cb8d0a91b959d4b6bc1aac250a7ee7e70329/src/build_info/build_dependency.rs#L78

This gets only one include, which affected us as we needed to include a new dependency which had three separate include folders.

**Comment by awakecoding** [comment]
@taco-paco FYI

I don't know when I'll get a chance to fix this to properly support multiple include directories, but I would definitely welcome a pull request for such an improvement
