### ISSUE TITLE
No option for setting options

### ISSUE THREAD

**Issue by raspofabs** [Devolutions/conan-rs#9]
In `InstallCommandBuilder `there is a `with_profile` and other settings related fluent methods, but there is no method to set options (which are required for using some packages.)

We've worked around this issue for a while locally with environment variables, but it would save us hacking to add something like `with_option` to set an option.

**Comment by awakecoding** [comment]
The recent changes should make it easier to add generic settings passed with -s, I don't recall how conan options are different from settings (what's the command-line notation for options?) but they could be built in a similar way: https://github.com/Devolutions/conan-rs/blob/master/src/build_info/build_settings.rs#L97

**Comment by Tomcat-42** [comment]
Should be resolved by #17. Think we can close
